Netframework/Models/Music.cs
 using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Netframework.Models
{
    public class Music
    {
        [Key]
        public int ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public int? CategoryID { get; set; }
        public virtual Category Category { get; set; }
    }
}

Netframework/Controllers/MusicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Netframework.Data;
using Netframework.Models;
using Netframework.ViewModels;
using PagedList;

namespace Netframework.Controllers
{
    public class MusicsController : Controller
    {
        private NetframeworkContext db = new NetframeworkContext();

        // GET: Musics
        public ActionResult Index(string category, string search, int? page, string sortBy)
        {
            MusicIndexViewModel viewModel = new MusicIndexViewModel();
            var musics = db.Musics.Include(m => m.Category);
     
            if (!String.IsNullOrEmpty(category))
            {
                musics = musics.Where(m => m.Category.Name == category);
            }
            if (!String.IsNullOrEmpty(search))
            {
                musics = musics.Where(m => m.Name.Contains(search) ||
                m.Description.Contains(search) ||
                m.Category.Name.Contains(search));
            
                viewModel.Search = search;
            }
            viewModel.CatsWithCount = from matchingMusics in musics
                                      where matchingMusics.CategoryID != null
                                      group matchingMusics by
                                      matchingMusics.Category.Name into catGroup
                                      select new CategoryWithCount()
                                      {
                                          CategoryName = catGroup.Key,
                                          MusicCount = catGroup.Count()
                                      };

            if (!String.IsNullOrEmpty(category))
            {
                musics = musics.Where(m => m.Category.Name == category);
                viewModel.Category = category;
            }
            
            switch (sortBy)
            {
                case "price_lowest":
                    musics = musics.OrderBy(m =>m.Price);
                    break;
                case "price_highest":
                    musics = musics.OrderByDescending(m => m.Price);
                    break;
                default:
                    musics = musics.OrderBy(m => m.Name);
                    break;
                    
            }
            const int PageItems = 3;
            int currentPage = (page ?? 1);
            viewModel.Musics = musics.ToPagedList(currentPage, PageItems);
            viewModel.SortBy = sortBy;
            viewModel.Sorts = new Dictionary<string, string>
            {
                { "Price low to high", "price_lowest"},
                { "Price high to low", "price_highest"}
            };
            return View(viewModel);
        }

        // GET: Musics/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Music music = db.Musics.Find(id);
            if (music == null)
            {
                return HttpNotFound();
            }
            return View(music);
        }

        // GET: Musics/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name");
            return View();
        }

        // POST: Musics/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Price,Description,CategoryID")] Music music)
        {
            if (ModelState.IsValid)
            {
                db.Musics.Add(music);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", music.CategoryID);
            return View(music);
        }

        // GET: Musics/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Music music = db.Musics.Find(id);
            if (music == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", music.CategoryID);
            return View(music);
        }

        // POST: Musics/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Price,Description,CategoryID")] Music music)
        {
            if (ModelState.IsValid)
            {
                db.Entry(music).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", music.CategoryID);
            return View(music);
        }

        // GET: Musics/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Music music = db.Musics.Find(id);
            if (music == null)
            {
                return HttpNotFound();
            }
            return View(music);
        }

        // POST: Musics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Music music = db.Musics.Find(id);
            db.Musics.Remove(music);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Netframework/Views/Musics/Create.cshtml
@model Netframework.Models.Music

@{
    ViewBag.Title = "Create";
}
@Styles.Render("~/Content/MusicCreat")



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Create</h2>
        <h4>Music</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="creatform-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="creatform-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="creatform-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="creatform-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="creatform-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<div class="validator">
    <a href="https://validator.w3.org/nu/?doc=http://localhost:52744/Musics/Create">VerifyHTML5</a>
    <a href="https://jigsaw.w3.org/css-validator/validator?uri=http://localhost:52744/Content/MusicCreat.css">VerifyCSS3</a>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Netframework/Views/Musics/Delete.cshtml
@model Netframework.Models.Music

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Music</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
<div class="validator">
    <a href="https://validator.w3.org/nu/?doc=http://localhost:52744/Musics/Delete">VerifyHTML5</a>
    <a href="https://jigsaw.w3.org/css-validator/validator?uri=http://localhost:52744/Content/MusicCreat.css">VerifyCSS3</a>
</div>

Netframework/Views/Musics/Details.cshtml
@model Netframework.Models.Music

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Music</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<div class="validator">
    <a href="https://validator.w3.org/nu/?doc=http://localhost:52744/Musics/Details">VerifyHTML5</a>
    <a href="https://jigsaw.w3.org/css-validator/validator?uri=http://localhost:52744/Content/MusicCreat.css">VerifyCSS3</a>
</div>

Netframework/Views/Musics/Edit.cshtml
@model Netframework.Models.Music

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Music</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="editform-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="editform-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="editform-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="editform-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="editform-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<div class="validator">
    <a href="https://validator.w3.org/nu/?doc=http://localhost:52744/Musics/Edit">VerifyHTML5</a>
    <a href="https://jigsaw.w3.org/css-validator/validator?uri=http://localhost:52744/Content/MusicCreat.css">VerifyCSS3</a>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Netframework/Views/Musics/Index.cshtml
@*model IEnumerable<Netframework.Models.Music>*@
@model Netframework.ViewModels.MusicIndexViewModel
@using PagedList.Mvc
 
@{
    ViewBag.Title = "Index";
}

<head>
    @Styles.Render("~/Content/User")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

</head>
<div class="app">
    <div class="mod_profile">
        <div class="section_inner">
            <div class="profile_user">
                <img src="../../wwwroot/images/user.jpg" alt=" " class="profile_cover">
            </div>
            <div class="profile_tit">
                <h1>My personal account</h1>
            </div>
        </div>
    </div>
    <div class="main">
        <div class="profile_nav">
            <a class="like" href="#">The music I like</a>
            <a class="like" href="#">The song list I created</a>
            <a class="like" href="#">Focus</a>
        </div>
    </div>
</div>

<section class="td">
    <p>
        @(String.IsNullOrWhiteSpace (Model.Search)? "Showing all":"You search for" + Model.Search + " found")
        @Model.Musics.TotalItemCount songs
    </p>
    <p>
        @Html.ActionLink("Create New", "Create")
        @using (Html.BeginForm("Index", "Musics", FormMethod.Get))
        {
            <label>Filter by category:</label>
            @Html.DropDownListFor(vm => vm.Category, Model.CatFilterItems, "All");
            <label>Sort by:</label>
            @Html.DropDownListFor(vm => vm.SortBy, new SelectList(Model.Sorts, "Value", "Key"), "Default")
            <input type="Submit" value="Filter" />
            <input type="hidden" name="Search" id="Search" value="@Model.Search" />
        }
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Musics.First().Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Musics.First().Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Musics.First().Description)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Musics)
        {
            <tr>
                <td id="tdfirst">
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }
    </table>
    <div class="page">
        Page @(Model.Musics.PageCount <Model.Musics.PageNumber ? 0 : Model.Musics.PageNumber) of @Model.Musics.PageCount
        @Html.PagedListPager(Model.Musics, page => Url.Action("Index", new { category = Model.Category, Search = Model.Search, sortBy = Model.SortBy, page }))
    </div>
    <div class="validator">
        <a href="https://validator.w3.org/nu/?doc=http://localhost:52744/Musics/Index">Verify HTML5</a>
        <a href="https://jigsaw.w3.org/css-validator/validator?uri=http://localhost:52744/Content/user.css">Verify CSS3</a>
    </div>
</section>